default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= [ENV.fetch("MAX_THREADS", 5), ENV.fetch("DB_POOL", 5)].max %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  database: <%= ENV.fetch("DB_NAME", "#{File.basename(Rails.root)}_development") %>
  <<: *default

test:
  database: <%= ENV.fetch("DB_NAME", "#{File.basename(Rails.root)}_test") %>
  <<: *default

production:
  database: <%= ENV.fetch("DB_NAME", "#{File.basename(Rails.root)}_production") %>
  <<: *default
