name: tests_and_linters
on: [push]
jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.6'
          bundler-cache: true
      - run: bundle exec rake
      - run: bin/rails db:migrate RAILS_ENV=test
      - run: bin/test

  check-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.6'
          bundler-cache: true
      - run: bundle exec rake
      - run: bin/quality