name: tests_and_linters
on: [push]
jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.6'
      - name: Install dependencies
      - run: bundle install
      - run: rake db:setup
      - name: Run tests
      - run: bin/test

  check-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.6'
      - name: Install dependencies
      - run: bundle install
      - name: Run linters
      - run: bin/quality